#!/usr/bin/env python

#   DISABLED: libdbm calls exit() in some error conditions

from dbm import gnu as dbm
from tempfile import NamedTemporaryFile
import os

FIELDS = (
    b'NOT',
    b'Python:',
    b'',
    b'REALLY',
    b'intended',
    b'THERE',
)


with NamedTemporaryFile(suffix='.db', delete=False, dir='/dev/shm') as f:
    f.write(b'@')
    f.close()
    try:
        db = dbm.open(f.name, 'r')
        for f in FIELDS:
            x = db.get(f, None)

    finally:
        os.unlink(f.name)
